import { useMemo, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { useAppStore } from "@/store/useAppStore";

export default function GoalsView() {
  const { goals, templates, tasks, addGoal, deleteGoal } = useAppStore();
  const [form, setForm] = useState(null);
  const progress = useMemo(() => goals.map((goal) => { const completed = tasks.filter((task) => task.completed && task.templateId === goal.templateId); const value = goal.metric === "hours" ? completed.reduce((sum, task) => sum + (task.duration || 0), 0) : completed.length; return { ...goal, value, percent: Math.min(100, Math.round((value / goal.target) * 100)) }; }), [goals, tasks]);
  return <div><div className="flex justify-between mb-6"><div><h1 className="text-3xl font-semibold">Goals</h1><p className="text-muted-foreground mt-1">Track progress from completed flexible tasks.</p></div><button onClick={() => setForm({ templateId: templates[0]?.id || "", target: 10, metric: "completions", period: "monthly" })} className="rounded-lg bg-primary text-primary-foreground px-3 py-2"><Plus className="w-4 h-4" /></button></div><div className="grid gap-4 sm:grid-cols-2">{progress.map((goal) => <div key={goal.id} className="rounded-2xl border bg-card p-5"><div className="flex justify-between"><div><p className="font-semibold">{templates.find((item) => item.id === goal.templateId)?.title || "Deleted template"}</p><p className="text-sm text-muted-foreground">{goal.value} / {goal.target} {goal.metric === "hours" ? "hours" : "sessions"} · {goal.period}</p></div><button onClick={() => deleteGoal(goal.id)}><Trash2 className="w-4 h-4 text-destructive" /></button></div><div className="mt-4 h-2 rounded bg-muted"><div className="h-full rounded bg-indigo-500" style={{ width: `${goal.percent}%` }} /></div><p className="mt-2 text-sm font-medium">{goal.percent}% complete</p></div>)}</div>{!goals.length && <div className="rounded-xl border border-dashed py-10 text-center text-muted-foreground">Create a goal linked to a flexible template.</div>}{form && <form onSubmit={(e) => { e.preventDefault(); if (form.templateId) { addGoal(form); setForm(null); } }} className="mt-6 rounded-2xl border bg-card p-5 space-y-3"><h2 className="font-semibold">New goal</h2><select value={form.templateId} onChange={(e) => setForm({ ...form, templateId: e.target.value })} className="w-full border rounded p-2 bg-transparent">{templates.map((template) => <option key={template.id} value={template.id}>{template.title}</option>)}</select><div className="grid grid-cols-3 gap-3"><input type="number" min="1" value={form.target} onChange={(e) => setForm({ ...form, target: Number(e.target.value) })} className="border rounded p-2 bg-transparent" /><select value={form.metric} onChange={(e) => setForm({ ...form, metric: e.target.value })} className="border rounded p-2 bg-transparent"><option value="completions">Sessions</option><option value="hours">Hours</option></select><select value={form.period} onChange={(e) => setForm({ ...form, period: e.target.value })} className="border rounded p-2 bg-transparent"><option value="monthly">Monthly</option><option value="weekly">Weekly</option></select></div><button className="w-full rounded-lg bg-primary text-primary-foreground py-2">Save goal</button></form>}</div>;
}
